ShellCheck suggestions applied. #RN
- https://www.shellcheck.net/
- brew install shellcheck

diff --git a/shell/common/bin/edittags b/shell/common/bin/edittags
--- a/shell/common/bin/edittags
+++ b/shell/common/bin/edittags
@@ -7,12 +7,12 @@
 
 
 set -e
-which id3dit &> /dev/null || { echo 'id3dit not installed'; exit 1; }
+which id3dit &> /dev/null || { echo 'id3dit not found in PATH'; exit 1; }
 
 dir="$1"
 if [ "$dir" != "" ]; then
-	cd "$dir"
+	pushd "$dir"
 fi
 
-ls -la *.mp3 > /dev/null
-uxterm -geometry 130x40-2900+400 -e id3dit *.mp3 &
+ls -la ./*.mp3 > /dev/null
+uxterm -geometry 130x40-2900+400 -e id3dit ./*.mp3 &
